### ISSUE TITLE
Add `tags` kwarg to `k8s_deploy`

### ISSUE THREAD

**Issue by scasagrande** [fasterci/rules_gitops#35]
As a build systems developer, I would like the ability to add specific Bazel tags to the targets generated by the `k8s_deploy` macro.

In my current use case I have an `oci_image` target that is a dependency of a `k8s_deploy` target. I have to support several different developer platforms and so I apply an automatic platform transition to the image (eg: https://github.com/aspect-build/bazel-examples/blob/main/oci_python_image/hello_world/BUILD.bazel#L60)

However, since I don't want developers using Macbooks to constantly cross compile this image, I have added a `"manual"` tag to the `oci_image` target and all other targets that depends on it. This way when a developer is just trying to run `bazel build //...` they don't have to worry about cross compilation. If they need to build the image, or run a container test, they can enter that specific bazel target label.

**Comment by michaelschiff** [comment]
makes sense to me
